alias l='ls -alF'
alias gs='git status'
alias drmf='docker rm -f $(docker ps -aq)'
alias dirm='docker image rm -f $(docker image ls -q)'
alias dvrm='docker volume rm -f $(docker volume ls -q)'
alias dpsa='docker ps -a --format="table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"'
